name: my_family
description: A Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  get: ^4.6.5
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.5
  flutter_hex_color: ^2.0.0
  fluttertoast: ^8.1.1
  permission_handler: ^10.2.0
  loading_animation_widget: ^1.2.0+4
  expandable: ^5.0.1
  smooth_page_indicator: ^1.0.0+2
  dropdown_button2: ^1.8.9
  custom_check_box: ^0.0.4
  percent_indicator: ^4.2.2
  buttons_tabbar: ^1.3.6
  device_info_plus: ^8.0.0
  flutter_easylogger: ^2.3.3
  dio: ^5.0.1
  connectivity_plus: ^3.0.3
  intl: ^0.18.0
  awesome_dialog:
    git: https://github.com/A7mdlbanna/awesomeDialogs.git
  cached_network_image: ^3.2.3
  flutter_svg_provider: ^1.0.3
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  flutter_chat_ui: ^0.0.2
  table_calendar:
    git:
      url: https://github.com/A7mdlbanna/table_calendar
  socket_io_client: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/group_pic/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_bold.ttf
          weight: 700
        - asset: assets/fonts/roboto_medium.ttf
          weight: 500
        - asset: assets/fonts/roboto_regular.ttf
          weight: 400
