import 'package:get/get.dart';
import 'package:my_family/ui/resources/app_strings.dart';

class MyTranslations implements Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "ar": {
          'my_family': 'أسرتي',
          // TODO SPLASH
          'join_our_community': 'انضم إلى مجتمعنا',
          'already_member': 'عضوا فعلا؟',
          'login': 'تسجيل الدخول',
          'next': 'التالي',
          'skip': 'تخطي',

          // TODO LOGIN
          'family_name': 'إسم العائلة',
          'family_password': 'كلمة مرور العائلة',
          'confirm_password': 'تأكيد كلمة المرور',
          'enter_your_family_name': 'أدخل اسم عائلتك',
          'enter_password': 'ادخل كلمة المرور',
          'create_account': 'إنشاء حساب',
          'dont_have_account': 'ليس لديك حساب؟',
          'have_account': 'لدي حساب بالفعل',
          'login_success': 'تم تسجيل الدخول بنجاح',
          'login_fail': 'فشل تسجيل الدخول',

          // TODO CREATE ACCOUNT
          'create_an_account': 'انشئ حساب',
          'connect_with_family_today': 'تواصل مع عائلتك اليوم!',
          'name': 'الإسم',
          'enter_your_name': 'أدخل أسمك',
          'email_address': 'عنوان البريد الإلكتروني',
          'enter_your_email': 'أدخل بريدك الإلكتروني',
          'password': 'كلمة المرور',
          'enter_Your_password': 'ادخل رقمك السري',
          'parents': 'الوالدين',
          'other_parent_name': 'الاسم الآخر للوالد',
          'other_parent_email': 'البريد الإلكتروني الآخر للوالد',
          'optional': '(إختياري)',
          'helpers': 'المساعدين',
          'how_many_helpers': 'كم عدد المساعدين؟',
          'children': 'الأطفال',
          'how_many_children': 'كم طفل؟',
          'permissions': 'الصلاحيات',
          'admin': 'المسؤل',
          // TODO PERSONAL INFO
          'verify_personal_data': 'تحقق من البيانات الشخصية',
          'please_enter_your_name': 'من فضلك أدخل إسمك',
          'please_enter_your_email': 'رجاءا أدخل بريدك الإلكتروني',
          'please_enter_valid_email': 'الرجاء إدخال بريد إلكتروني صحيح',
          'please_enter_password': 'الرجاء إدخال كلمة المرور',
          'password_6_characters': 'يجب أن تكون كلمة المرور أكثر من 6 أحرف',
          // TODO FAMILY INFO
          'verify_family_data': 'تحقق من بيانات العائلة',
          'please_enter_your_family_name': 'الرجاء إدخال اسم عائلتك',
          'please_enter_your_family_password': 'الرجاء إدخال كلمة مرور عائلتك',
          'please_enter_confirm_password': 'الرجاء إدخال تأكيد كلمة المرور',
          'passwords_not_match': 'كلمتا المرور غير مطابقة',
          // TODO HELPER INFO
          'verify_helpers_data': 'تحقق من بيانات المساعدين',
          'please_enter_first_helper_email': 'الرجاء إدخال البريد الإلكتروني للمساعد الأول',
          'please_select_first_helper_permissions': 'الرجاء تحديد أذونات المساعد الأول',
          'please_enter_second_helper_email': 'الرجاء إدخال البريد الإلكتروني للمساعد الثاني',
          'please_select_second_helper_permissions': 'الرجاء تحديد أذونات المساعد الثاني',
          'please_enter_third_helper_email': 'الرجاء إدخال البريد الإلكتروني للمساعد الثالث',
          'please_select_third_helper_permissions': 'الرجاء تحديد أذونات المساعد الثالث',
          'please_enter_fourth_helper_email': 'الرجاء إدخال البريد الإلكتروني للمساعد الرابع',
          'please_select_fourth_helper_permissions': 'الرجاء تحديد أذونات المساعد الرابع',
          'must_select_one_helper': 'يجب اختيار مساعد واحد على الأقل',
          // TODO CHILD INFO
          'verify_children_data': 'تحقق من بيانات الأطفال',
          'please_enter_first_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الأول',
          'please_enter_second_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الثاني',
          'please_enter_third_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الثالث',
          'please_enter_fourth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الرابع',
          'please_enter_fivth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الخامس',
          'please_enter_sixth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل السادس',
          'please_enter_sevnth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل السابع',
          'please_enter_eighth_child_email': 'الرجاء إدخال البريد الإلكتروني للطفل الثامن',
          'must_select_one_child': 'يجب اختيار طفل واحد على الأقل',

          // TODO HOME
          'home': 'الرئيسية',
          'calendar': 'التقويم',
          'messages': 'الرسائل',
          'family': 'العائلة',
          'entertainment': 'الترفيه',
          'study': 'المذاكرة',
          'to_do_list': 'عمل قائمة',
          'add_entertainment': 'أضف ترفيه',
          'add_title_entertainment': 'أضف عنوانًا لعطلة نهاية الأسبوع هذه للترفيه' ,
          'add_title': 'أضف عنوانا',
          'add_suggestions': 'إضافة اقتراحات؟',
          'subjects': 'المواضيع',
          'assignments': 'الاختبارات',
          'add_study': 'أضف دراسة',
          'choose-child_assignment': 'اختر الطفل الذي يجب أن يسلم المهمة',
          'how_many_subjects': 'كم عدد المواضيع؟',
          'add_title_Subject': 'أضف عنوان الموضوع',
          'name_child': 'Name of Child',
          'send': 'رسال',
          'profile': 'الصفحة الشخصية',

          'add_task': 'اضف مهمة',
          'choose-child_todo': 'اختر الطفل الذي يجب أن يفعل المهمة',
          'how_many_tasks': 'كم عدد المهام؟',



          //TODO CHAT
          'create_group': 'إنشاء مجموعة',
          'group_name': 'أسم المجموعة',
          'participants': 'مشاركون :',
          'description': 'وصف',
          'of': 'الى',
          'choose_an_avatar_for_family_group': 'اختر صورة رمزية لمجموعة العائلة',
          'save': 'حفظ',



          // TODO MESSAGES
          'groups': 'مجموعات',

          // TODO SETTINGS
          'settings': 'الإعدادات',
          'edit_account': 'تعديل الحساب',
          'themes': 'لون التطبيق',
          'language': 'اللغة',
          'arabic': 'العربية',
          'english': 'الإنجليزية',
          'about': 'عن التطبيق',
          'help': 'مساعدة',
          'logout': 'تسجيل الخروج',
          'cancel': 'إلغاء',
          'notifications': ' الاشعارات',
          "please_login": "الرجاء تسجيل الدخول أولاً للمتابعة \n لأنك الآن في وضع الضيف",
          'text_log_out': 'هل أنت متأكد من عملية \nالخروج من التطبيق',
          'about_app': 'عن التطبيق',
          'our_vision': 'رؤيتنا',
          'our_mission': 'مهمتنا',
          'our_service': 'خدماتنا',
          'about_app_body': 'تطبيق العائلة هو منصة شاملة مصممة لتيسير التواصل والتنظيم والتعاون بين أفراد العائلة. إنه أداة شاملة توفر مجموعة من الخدمات لمساعدة العائلات على البقاء متصلة ومنظمة.',
          'our_vision_body': 'نتطلع إلى عالم يمكن للعائلات فيه البقاء متصلة ومنظمة بكل سهولة، بغض النظر عن المسافات أو الجداول الزمنية المزدحمة. هدفنا هو إنشاء منصة تبسط حياة العائلة وتعزز العلاقات القوية بين أفراد الأسرة.',
          'our_mission_body': 'مهمتنا هي توفير منصة سهلة الاستخدام وموثوقة للعائلات تمكنهم من التواصل والتنظيم والتعاون بشكل فعال. نحن نسعى لتقديم مجموعة واسعة من الميزات والخدمات التي تلبي احتياجات العائلات الحديثة المتنوعة، من التقويمات المشتركة وقوائم المهام إلى الرسائل ومشاركة الصور.',
          'our_service_body': 'يوفر تطبيق العائلة لدينا مجموعة واسعة من الخدمات لمساعدة العائلات على البقاء منظمة ومتصلة. تتضمن هذه الخدمات التقويمات المشتركة وقوائم المهام والرسائل ومشاركة الصور وغيرها. صمم تطبيقنا ليكون سهل الاستخدام ومتاحًا لجميع أفراد العائلة، بغض النظر عن العمر أو الخبرة التقنية.',
          'problem_title': 'عنوان المشكلة',
          'enter_problem_title': 'أدخل عنوان المشكلة',
          'problem_explain': 'شرح المشكلة',
          'enter_problem_explain': 'أدخل وصفًا للمشكلة',
          'add_problem_picture': 'أضف صورة للمشكلة',
          'edit_family_info': 'تعديل معلومات العائلة',
          'edit_family_password': 'تعديل كلمة مرور العائلة',
          'add_family_member': 'إضافة عضو للعائلة',
          AppStrings.memberType: 'نوع العضو',
          AppStrings.familyMember: 'اعضاء العائلة',
          AppStrings.chooseFamilyAvatar: 'اختار صورة للمجموعة',
          AppStrings.updateProfile: 'تحديث الحساب الشخصي',
          AppStrings.takePicture: 'التفاط صورة',
          AppStrings.chooseFromGallery: 'اختر من المعرض',
          AppStrings.createNewPass: 'إنشاء كلمة مرور جديدة للعائلة',
          AppStrings.createNewPassMsg: 'يجب أن تختلف كلمة المرور الجديدة عن كلمات المرور السابقة المستخدمة.',
          AppStrings.newPass: 'كلمة المرور الجديدة',
          AppStrings.passConf: 'تأكيد كلمة المرور',
          AppStrings.mustMatch: 'يجب أن تتطابق كلمتي المرور',
          AppStrings.deactivateAccount: 'الغاء الحساب',
          AppStrings.deactivateAccountMsg: 'هل انت متاكد من الغاء حسابك؟',
          AppStrings.deactivateSuccess: 'تم الغاء حسابك',
          AppStrings.deactivateFailed: 'الغاء الحساب فشل',

          AppStrings.noEvents: 'لا يوجد احداث اليوم',
          AppStrings.addEvent: 'اضف حدث جديد',
          AppStrings.eventName: 'اسم الحدث',
          AppStrings.eventNote: 'ادخل وصل الحدث هنا',
          AppStrings.date: 'التاريخ',
          AppStrings.startTime: 'وقت البدء',
          AppStrings.endTime: 'وقت الانتهاء',
          AppStrings.createEvent: 'انشئ حدث',
          AppStrings.remindMe: 'ذكرني',
          AppStrings.typing: 'يكتب...',
          AppStrings.noNotifications: 'لا يوجد اشعارات حاليا',
          AppStrings.forward: 'اعادة توجيه',
        },
        "en": {
          'my_family': 'My Family',
          // TODO SPLASH
          'join_our_community': 'Join our community',
          'already_member': 'Already a member?',
          'login': 'Login',
          'next': 'Next',
          'skip': 'Skip',

          // TODO LOGIN
          'family_name': 'Family Name',
          'family_password': 'Family Password',
          'confirm_password': '​Confirm Password',
          'enter_your_family_name': 'Enter Your Family Name',
          'enter_password': 'Enter password',
          'create_account': 'Create account',
          'dont_have_account': 'Don\'t have an account?',
          'have_account': 'I already have an account',
          'login_success': 'Logged in successfully',
          'login_fail': 'Login failed',


          // TODO CREATE ACCOUNT
          'create_an_account': 'Create an account',
          'connect_with_family_today': 'Connect with your family today !',
          'name': 'Name',
          'enter_your_name': 'Enter your name',
          'email_address': 'Email​ Address',
          'enter_your_email': 'Enter your email',
          'password': 'Password',
          'enter_Your_password': 'Enter Your Password',
          'parents': 'Parents',
          'other_parent_name': 'The other parent name',
          'other_parent_email': 'The other parent email',
          'optional': '(optional)',
          'helpers': 'Helpers',
          'how_many_helpers': 'How many helpers?',
          'children': 'Children',
          'how_many_children': 'How many children?',
          'permissions': 'Permissions',
          'admin': 'Admin',
          'register_success': 'Account created successfully',
          'register_fail': 'Account creation failed',

          // TODO PERSONAL INFO
          'verify_personal_data': 'Verify personal data',
          'please_enter_your_name': 'Please enter your name',
          'please_enter_your_email': 'Please enter your email',
          'please_enter_valid_email': 'please enter a working email address',
          'please_enter_password': 'Please enter password',
          'password_6_characters': 'Password must be more than 6 characters long',
          // TODO FAMILY INFO
          'verify_family_data': 'Verify family data',
          'please_enter_your_family_name': 'Please enter your family name',
          'please_enter_your_family_password': 'Please enter your family password',
          'please_enter_confirm_password': 'Please enter confirm password',
          'passwords_not_match': 'Passwords do not match',
          // TODO HELPER INFO
          'verify_helpers_data': 'Verify helpers data',
          'please_enter_first_helper_email': 'Please enter the email of the first assistant',
          'please_select_first_helper_permissions': 'Please select first helper permissions',
          'please_enter_second_helper_email': 'Please enter the email of the second assistant',
          'please_select_second_helper_permissions': 'Please select second helper permissions',
          'please_enter_third_helper_email': 'Please enter the email of the third assistant',
          'please_select_third_helper_permissions': 'Please select third helper permissions',
          'please_enter_fourth_helper_email': 'Please enter the email of the fourth assistant',
          'please_select_fourth_helper_permissions': 'Please select fourth helper permissions',
          'must_select_one_helper': 'At least one assistant must be selected',
          // TODO ChILD INFO
          'verify_chidren_data': 'Verify children data',
          'please_enter_first_child_email': 'Please enter the email of the first child',
          'please_enter_second_child_email': 'Please enter the email of the second child',
          'please_enter_third_child_email': 'Please enter the email of the third child',
          'please_enter_fourth_child_email': 'Please enter the email of the fourth child',
          'please_enter_fivth_child_email': 'Please enter the email of the fivth child',
          'please_enter_sixth_child_email': 'Please enter the email of the sixth child',
          'please_enter_sevnth_child_email': 'Please enter the email of the sevnth child',
          'please_enter_eighth_child_email': 'Please enter the email of the eighth child',
          'must_select_one_child': 'At least one child must be selected',


          // TODO LOUGOUT
          'logout_success': 'Logged out successfully',
          'logout_fail': 'Logout failed',

          // TODO HOME
          'home': 'Home',
          'calendar': 'Calendar',
          'messages': 'Messages',
          'family': 'Family',
          'entertainment': 'Entertainment',
          'study': 'Study',
          'to_do_list': 'To-Do List',
          'add_entertainment': 'Add Entertainment',
          'add_title_entertainment': 'Add Title for this weekend,s Entertainment' ,
          'add_title': 'Add Title',
          'add_suggestions': 'Add suggestions?',
          'subjects': 'Subjects',
          'assignments': 'Assignments',
          'add_study': 'Add Study',
          'choose-child_assignment': 'Choose the child who has to hand over the \n assignment',
          'how_many_subjects': 'How many Subjects?',
          'add_title_Subject': 'Add Title of Subject',
          'name_child': 'Name of Child',
          'send': 'Send',
          'profile': 'Profile',
          'add_task': 'Add Task',
          'choose-child_todo': 'Choose the child who has to hand over the Task',
          'how_many_tasks': 'How many Tasks?',
          'how_many_suggestions': 'How many Suggestions?',


          //TODO CHAT
          'create_group': 'Create Group',
          'group_name': 'Group Name',
          'description': 'Description',
          'participants': 'PARTICIPANTS :',
          'of': '0F',
          'choose_an_avatar_for_family_group': 'Choose An Avatar For Family Group',
          'save': 'Save',


          // TODO MESSAGES
          'groups': 'Groups',

          // TODO SETTINGS
          'settings': 'Settings',
          'edit_account': 'Edit account',
          'themes': 'Themes',
          'language': 'Language',
          'arabic': 'Arabic',
          'english': 'English',
          'about': 'About',
          'help': 'Help',
          'logout': 'Log out',
          'cancel': 'Cancel',
          'notifications': ' Notifications',
          "please_login": "Please login first to continue \nBecause you are now in guest mode",
          'text_log_out': 'Are you sure about the checkout\n process  from the app',
          'about_app': 'About The App',
          'our_vision': 'Our Vision',
          'our_mission': 'Our Mission',
          'our_service': 'Our Service',
          'about_app_body': 'Our Family App is a comprehensive platform designed to facilitate communication, organization, and collaboration among family members. It is an all-in-one tool that provides a range of services to help families stay connected and organized.',
          'our_vision_body': 'We envision a world where families can stay connected and organized effortlessly, regardless of distance or busy schedules. Our goal is to create a platform that simplifies family life and fosters stronger relationships among family members.',
          'our_mission_body': 'Our mission is to provide families with a user-friendly and reliable platform that enables them to communicate, organize, and collaborate effectively. We strive to offer a wide range of features and services that meet the diverse needs of modern families, from shared calendars and to-do lists to messaging and photo sharing.',
          'our_service_body': 'Our Family App offers a wide range of services to help families stay organized and connected. These services include shared calendars, to-do lists, messaging, photo sharing, and more. Our app is designed to be user-friendly and accessible to all family members, regardless of age or technical proficiency.',
          'problem_title': 'Problem Title',
          'enter_problem_title': 'Enter the title of the problem',
          'problem_explain': 'Problem Explanation',
          'enter_problem_explain': 'Enter an explanation for the problem',
          'add_problem_picture': 'Add a picture of the problem',
          'edit_family_info': 'Edit Family Information',
          'edit_family_password': 'Edit Family Password',
          'add_family_member': 'Add Family Member',
          AppStrings.memberType: 'Member Type',
          AppStrings.familyMember: 'Family Members',
          AppStrings.chooseFamilyAvatar: 'Choose An Avatar For Family Group',
          AppStrings.updateProfile: 'Update Profile',
          AppStrings.takePicture: 'Take a picture',
          AppStrings.chooseFromGallery: 'Choose From Gallery',
          AppStrings.createNewPass: 'Create new family password',
          AppStrings.createNewPassMsg: 'your new password must the different form previous used passwords.',
          AppStrings.newPass: 'New Password',
          AppStrings.passConf: 'Confirm Password',
          AppStrings.mustMatch: 'Both passwords must match',
          AppStrings.deactivateAccount: 'Delete Account',
          AppStrings.deactivateAccountMsg: 'Are your sure you want to Delete your account?',
          AppStrings.deactivateSuccess: 'Account Deleted Successfully',
          AppStrings.deactivateFailed: 'Couldn\'t Delete Account',
          AppStrings.noEvents: 'There are no events today',
          AppStrings.addEvent: 'Add New Event',
          AppStrings.eventName: 'Event name',
          AppStrings.eventNote: 'Type the note here...',
          AppStrings.date: 'Date',
          AppStrings.startTime: 'Start time',
          AppStrings.endTime: 'End time',
          AppStrings.createEvent: 'Create Event',
          AppStrings.remindMe: 'Remind me',
          AppStrings.typing: 'typing...',
          AppStrings.noNotifications: 'There is no notifications in the meantime',
          AppStrings.forward: 'forward'
        },
      };
}
